version: "2"

services:
  server:
    build: .
    command: serve --http=0.0.0.0:8090
    volumes:
      - ./.data:/app/.data
    ports:
      - "8090:8090"
    environment:
      - ENV=prod
    restart: unless-stopped
    networks:
      - tunnel

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token $CLOUDFLARED_TOKEN
    networks:
      - tunnel
    restart: unless-stopped
    environment:
      - CLOUDFLARED_TOKEN=${CLOUDFLARED_TOKEN}

networks:
  tunnel:
